---
# Copyright (C) 2021 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (SuSE compatible OS) Install required packages
  ansible.builtin.package:
    name: "{{ packages_suse }}"
    state: present
  loop:
    - lvm2
    - util-linux
  loop_control:
    loop_var: packages_suse

- name: (SuSE compatible OS) Install additional packages
  ansible.builtin.package:
    name: "{{ packages_suse }}"
    state: present
  loop: "{{ additional_packages_suse }}"
  loop_control:
    loop_var: packages_suse
