---
# Copyright (C) 2021 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 192
      cpus: 2

platforms:
  - name: test-lvm-ubuntu2004
    box: generic/ubuntu2004
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
      - "storage :file, :type => 'qcow2', :device => 'vdc', :size => '1G'"
      - "storage :file, :type => 'qcow2', :device => 'vdd', :size => '1G'"
      - "storage :file, :type => 'qcow2', :device => 'vde', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint

scenario:
  name: kvm-vg-only
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: False
