---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Include LVM role
  hosts: test-lvm-ubuntu2204
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-ubuntu2004
  vars_files:
    - vars/test-lvm-ubuntu2004_create.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-fedora39
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-fedora36
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-centos7
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_create.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_delete.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-opensuse-leap-15-4
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-opensuse-leap-15-5
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-debian11
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role
  hosts: test-lvm-debian12
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role Rocky Linux 8
  hosts: test-lvm-rocky8
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role Rocky Linux 9
  hosts: test-lvm-rocky9
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role Almalinux 8
  hosts: test-lvm-alma8
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Include LVM role Almalinux 9
  hosts: test-lvm-alma9
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm
