---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Prepare Archlinux
  hosts: test-lvm-arch
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      failed_when: false

    - name: Updating pacman cache
      ansible.builtin.raw: pacman -Sy
      changed_when: false
      failed_when: false

    - name: Install Python
      ansible.builtin.raw: |
        pacman -S --noconfirm python
      args:
        executable: /bin/bash
      changed_when: false

- name: Prepare Ubuntu
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: (Ubuntu) Update APT package cache
      when: ansible_distribution | lower == 'ubuntu'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
