---
# Copyright (C) 2021-2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: (Archlinux) setup
      block:
        - name: (Archlinux) Init pacman
          raw: |
            pacman-key --init
            pacman-key --populate archlinux
          changed_when: false
          ignore_errors: true

        - name: (Archlinux) Update pacman cache
          community.general.pacman:
            update_cache: true
          changed_when: false
      when: ansible_distribution | lower == 'archlinux'

    - name: (Ubuntu) Update APT package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_distribution | lower == 'ubuntu'
